### ISSUE TITLE
能否将各个功能分离成单独纯净版?

### ISSUE THREAD

**Issue by GEFNENEN** [luotengyuan/MyScreenTools#1]
我只想要个屏幕识别翻译~~~
截图, 取色啥的用惯了别的辣~

**Comment by luotengyuan** [comment]
花了几分钟将你说的功能提取出来，代码在ocr_lite分支，安装包请下载以下链接，希望能够帮到你。
[MyScreenToolsSetup（ocr_lite）_V1.0.0.0.zip](https://github.com/luotengyuan/MyScreenTools/files/9626413/MyScreenToolsSetup.ocr_lite._V1.0.0.0.zip)
